export const tableHeadings = [
  "sales_and_marketing_performance_metrics_summary_table",
  "customer_transaction_history_by_product_category",
  "employee_training_and_certification_records",
  "inventory_management_system_audit_log",
  "financial_analysis_and_reporting_dashboard_data",
  "product_catalogue_and_pricing_information",
  "customer_feedback_and_satisfaction_survey_results",
  "vendor_relationship_management_database",
  "production_planning_and_scheduling_system",
  "human_resources_performance_appraisal_records",
  "supply_chain_optimization_model_data",
  "research_and_development_experiment_results",
  "customer_relationship_management_system_data",
  "enterprise_resource_planning_integration_logs",
  "quality_control_inspection_reports",
  "shipping_and_logistics_management_dashboard",
  "market_research_and_analysis_database",
  "online_customer_support_ticketing_system",
  "warehouse_inventory_tracking_and_management",
  "financial_transactions_and_ledger_entries",
  "employee_time_tracking_and_attendance_records",
  "manufacturing_process_performance_metrics",
  "customer_demographic_and_behavioral_data",
  "project_management_and_task_assignment_logs",
  "social_media_engagement_and_analytics_data",
  "health_and_safety_incident_reporting_database",
  "product_testing_and_quality_assurance_results",
  "customer_purchase_history_and_preferences",
  "vendor_performance_evaluation_metrics",
  "employee_compensation_and_benefits_records",
  "data_security_and_access_control_audit_logs",
  "online_sales_and_revenue_forecasting_models",
  "customer_service_interaction_logs_and_metrics",
  "inventory_replenishment_and_ordering_system",
  "financial_budgeting_and_planning_documents",
  "employee_skill_inventory_and_training_needs",
  "product_lifetime_value_and_profitability_analysis",
  "customer_complaint_resolution_tracking",
  "supplier_contract_management_database",
  "marketing_campaign_performance_metrics",
  "production_yield_and_efficiency_reports",
  "employee_recruitment_and_applicant_tracking",
  "customer_retention_and_churn_analysis",
  "ecommerce_platform_transaction_data",
  "inventory_shrinkage_and_loss_prevention_reports",
  "financial_statement_preparation_documents",
  "employee_engagement_and_satisfaction_survey_results",
  "customer_lifetime_value_prediction_models",
  "supplier_payment_and_invoicing_records",
];

export const queries = [
  "SELECT * FROM table1",
  "SELECT column1, column2 FROM table2",
  "INSERT INTO table3 (column1, column2) VALUES (value1, value2)",
  "UPDATE table4 SET column1 = value1 WHERE condition",
  "DELETE FROM table5 WHERE condition",
  "SELECT column1, column2, column3 FROM table6",
  "SELECT * FROM table7 WHERE condition",
  "INSERT INTO table8 (column1, column2, column3) VALUES (value1, value2, value3)",
  "UPDATE table9 SET column1 = value1, column2 = value2 WHERE condition",
  "DELETE FROM table10",
];

export const employees = [
  {
    id: 1,
    name: "John Doe",
    position: "Software Engineer",
    age: 30,
    department: "Engineering",
    salary: 5000,
    location: "New York",
    email: "john.doe@example.com",
  },
  {
    id: 2,
    name: "Jane Smith",
    position: "UI/UX Designer",
    age: 28,
    department: "Design",
    salary: 4500,
    location: "San Francisco",
    email: "jane.smith@example.com",
  },
  {
    id: 3,
    name: "Mike Johnson",
    position: "Product Manager",
    age: 35,
    department: "Product Management",
    salary: 6000,
    location: "London",
    email: "mike.johnson@example.com",
  },
  {
    id: 4,
    name: "Sarah Williams",
    position: "Frontend Developer",
    age: 32,
    department: "Engineering",
    salary: 5500,
    location: "Berlin",
    email: "sarah.williams@example.com",
  },
  {
    id: 5,
    name: "David Brown",
    position: "Backend Developer",
    age: 29,
    department: "Engineering",
    salary: 5200,
    location: "New York",
    email: "david.brown@example.com",
  },
  {
    id: 6,
    name: "Emily Davis",
    position: "Graphic Designer",
    age: 27,
    department: "Design",
    salary: 4200,
    location: "San Francisco",
    email: "emily.davis@example.com",
  },
  {
    id: 7,
    name: "Michael Wilson",
    position: "Product Designer",
    age: 33,
    department: "Design",
    salary: 4800,
    location: "London",
    email: "michael.wilson@example.com",
  },
  {
    id: 8,
    name: "Jessica Taylor",
    position: "Project Manager",
    age: 31,
    department: "Product Management",
    salary: 5800,
    location: "Berlin",
    email: "jessica.taylor@example.com",
  },
  {
    id: 9,
    name: "Andrew Anderson",
    position: "Software Engineer",
    age: 34,
    department: "Engineering",
    salary: 5300,
    location: "New York",
    email: "andrew.anderson@example.com",
  },
  {
    id: 10,
    name: "Olivia Martinez",
    position: "UI/UX Designer",
    age: 26,
    department: "Design",
    salary: 4400,
    location: "San Francisco",
    email: "olivia.martinez@example.com",
  },
  {
    id: 11,
    name: "Daniel Clark",
    position: "Product Manager",
    age: 36,
    department: "Product Management",
    salary: 6100,
    location: "London",
    email: "daniel.clark@example.com",
  },
  {
    id: 12,
    name: "Daniel Clark",
    position: "Product Manager",
    age: 36,
    department: "Product Management",
    salary: 6100,
    location: "London",
    email: "daniel.clark@example.com",
  },
  {
    id: 13,
    name: "Daniel Clark",
    position: "Product Manager",
    age: 36,
    department: "Product Management",
    salary: 6100,
    location: "London",
    email: "daniel.clark@example.com",
  },
  {
    id: 14,
    name: "Daniel Clark",
    position: "Product Manager",
    age: 36,
    department: "Product Management",
    salary: 6100,
    location: "London",
    email: "daniel.clark@example.com",
  },
  {
    id: 15,
    name: "Daniel Clark",
    position: "Product Manager",
    age: 36,
    department: "Product Management",
    salary: 6100,
    location: "London",
    email: "daniel.clark@example.com",
  },
  {
    id: 16,
    name: "Daniel Clark",
    position: "Product Manager",
    age: 36,
    department: "Product Management",
    salary: 6100,
    location: "London",
    email: "daniel.clark@example.com",
  },
  {
    id: 17,
    name: "Daniel Clark",
    position: "Product Manager",
    age: 36,
    department: "Product Management",
    salary: 6100,
    location: "London",
    email: "daniel.clark@example.com",
  },
  {
    id: 18,
    name: "Daniel Clark",
    position: "Product Manager",
    age: 36,
    department: "Product Management",
    salary: 6100,
    location: "London",
    email: "daniel.clark@example.com",
  },
  {
    id: 19,
    name: "Daniel Clark",
    position: "Product Manager",
    age: 36,
    department: "Product Management",
    salary: 6100,
    location: "London",
    email: "daniel.clark@example.com",
  },
  {
    id: 20,
    name: "Daniel Clark",
    position: "Product Manager",
    age: 36,
    department: "Product Management",
    salary: 6100,
    location: "London",
    email: "daniel.clark@example.com",
  },
  {
    id: 21,
    name: "Daniel Clark",
    position: "Product Manager",
    age: 36,
    department: "Product Management",
    salary: 6100,
    location: "London",
    email: "daniel.clark@example.com",
  },
  {
    id: 22,
    name: "Daniel Clark",
    position: "Product Manager",
    age: 36,
    department: "Product Management",
    salary: 6100,
    location: "London",
    email: "daniel.clark@example.com",
  },
  {
    id: 23,
    name: "Daniel Clark",
    position: "Product Manager",
    age: 36,
    department: "Product Management",
    salary: 6100,
    location: "London",
    email: "daniel.clark@example.com",
  },
  {
    id: 24,
    name: "Daniel Clark",
    position: "Product Manager",
    age: 36,
    department: "Product Management",
    salary: 6100,
    location: "London",
    email: "daniel.clark@example.com",
  },
  {
    id: 25,
    name: "Daniel Clark",
    position: "Product Manager",
    age: 36,
    department: "Product Management",
    salary: 6100,
    location: "London",
    email: "daniel.clark@example.com",
  },
  {
    id: 26,
    name: "Daniel Clark",
    position: "Product Manager",
    age: 36,
    department: "Product Management",
    salary: 6100,
    location: "London",
    email: "daniel.clark@example.com",
  },
];
